version: '3.1'

services:
  server:
    build: .
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - "7000:7000"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 7005:7005
    volumes:
      - ./dashboard:/home/node/code:delegated
      - /home/node/code/node_modules/